config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
  	resources :messages, only: [:index, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :message
  has_many :user_groups
  has_many :users, through: :user_groups
  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  # validates :content, presence: true, unless: :image?
  # mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messsges
  has_many :user_groups
  has_many :groups, through: :user_groups
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
  	@group = Group.new
  	@group.users << current_user
  end

  def create
  	@group = Group.new(group_params)
  	if @group.save
  	  redirect_to root_path, notice: 'グループを作成しました'
  	else
  	  render :new
  	end
  end

  def edit
  end

  def update
  	if @group.update(group_params)
  	  redirect_to group_messages_path(@group), notice: 'グループを編集しました'
  	else
  	  render :edit
  	end
  end

  private
  def group_params
  	params.require(:group).permit(:name,  user_ids: [])
  end

  def set_group
  	@group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    /
      <div class='chat-group-form__field--left'>
      <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
      </div>
      <div class='chat-group-form__field--right'>
      <div class='chat-group-form__search clearfix'>
      <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
      </div>
      <div id='user-search-result'></div>
      </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div id='chat-group-users'>
        <div class='chat-group-user clearfix' id='chat-group-user-22'>
        <input name='chat_group[user_ids][]' type='hidden' value='22'>
        <p class='chat-group-user__name'>seo_kyohei</p>
        </div>
        </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.side-content
  = render "messages/side-hedder"
  = render "messages/side-groups"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_main-body.html.haml
.main-body
  .main-body__main-posts
    .message
      .message__message-hedder
        %p.message__message-hedder__name
          Nozomu Machida
        %p.message__message-hedder__time
          2016/10/02 06:27:07
      .message__body
        %p.body
          なるほど

      .message__message-hedder
        %p.message__message-hedder__name
          ryosukemaehira
        %p.message__message-hedder__time
          2016/10/02 06:27:14
      .message__body
        %p.body
          command Enterで送信したい感ある

      .message__message-hedder
        %p.message__message-hedder__name
          ryosukemaehira
        %p.message__message-hedder__time
          2016/10/02 06:27:30
      .message__body
        %p.body
          お腹すいた

app/views/messages/_main-form.html.haml
.footer

  .form
    .form__message
      %input{ type: "text", placeholder: "type a message"}
      %i.fa.fa-image
    .form__button
      %input{ type: "button", value: "Send"}

app/views/messages/_main-hedder.html.haml
.main-hedder
  .main-hedder__left
    %h2
      sampleグループ
    %p
      Members:xxxxxxxxxxx@gmail.com
  .main-hedder__right
    %input{ type: "button", value: "Edit" }

app/views/messages/_side-groups.html.haml
.side-groups
  - current_user.groups.each do |group|
    .side-group
      = link_to group_messages_path(group) do
        .side-group__name
          = group.name
        .side-group__message
          メッセージはありません。

app/views/messages/_side-hedder.html.haml
.side-hedder
  %h5.side-hedder__user-name
    = current_user.name
  .side-hedder__icons
    = link_to new_group_path do
      %i.fa.fa-pencil-square-o
    = link_to edit_user_path(current_user) do
      %i.fa.fa-cog

app/views/messages/index.html.haml
.side-content
  = render "side-hedder"
  = render "side-groups"
.main-content
  = render "main-hedder"
  = render "main-body"
  = render "main-form"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'